# Generated by Django 6.0.3 on 2026-03-31 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='URLModel',
        ),
    ]
