# Generated by Django 6.0.3 on 2026-04-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortapp', '0002_rename_url_urlmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
