# Generated by Django 6.0.3 on 2026-04-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortapp', '0003_urlmodel_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code/'),
        ),
    ]
