# Generated by Django 6.0.4 on 2026-04-13 03:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortapp', '0004_urlmodel_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
