# Generated by Django 5.2.13 on 2026-08-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortapp', '0006_clickevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
